/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app_pack;
import java.util.Date;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import java.util.Random;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author 2004d
 */
public class signUp extends javax.swing.JFrame {
    
    static String old_mail,new_mail;
    String OTP = "";
    PreparedStatement stm;
    Connection con;
    static ResultSet data;

    /**
     * Creates new form signUp
     */
    public signUp() {
        
        
        try
        {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3306/college_mgt";
        String user = "root";
        String password = "0000";
        con = DriverManager.getConnection(url,user,password);
//        String q1 = "select * from data1";
//        sm = (PreparedStatement) con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Cannot connect to the database.\n Please ask the developer to take care of this bug.","ERROR", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
            System.exit(0);
        }
        setIconImage();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        otp = new javax.swing.JTextField();
        verifyotp = new javax.swing.JButton();
        sendotp = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pass2 = new javax.swing.JPasswordField();
        pass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        signin = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        adhar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");
        setBackground(new java.awt.Color(153, 255, 102));
        setLocation(new java.awt.Point(550, 150));
        setName("SignUp"); // NOI18N
        setPreferredSize(new java.awt.Dimension(747, 809));
        setResizable(false);
        setSize(new java.awt.Dimension(738, 798));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 237, 219));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 4));

        jPanel1.setBackground(new java.awt.Color(221, 117, 110));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SignUp");
        jPanel1.add(jLabel5);

        jPanel3.setBackground(new java.awt.Color(255, 237, 219));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(242, 242, 61));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("UserName");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 210, 50));

        username.setBackground(new java.awt.Color(255, 198, 172));
        username.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        username.setToolTipText("Enter Your Name.");
        username.setMargin(new java.awt.Insets(1, 3, 1, 1));
        username.setOpaque(true);
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameKeyReleased(evt);
            }
        });
        jPanel3.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 290, 50));

        jLabel1.setBackground(new java.awt.Color(242, 242, 61));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Email ID");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 210, 50));

        mail.setBackground(new java.awt.Color(255, 198, 172));
        mail.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        mail.setToolTipText("Enter valid email id to receive the OTP to proceed further. ");
        mail.setMargin(new java.awt.Insets(1, 3, 1, 1));
        mail.setOpaque(true);
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mailKeyReleased(evt);
            }
        });
        jPanel3.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 290, 50));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("O.T.P.");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 210, 50));

        otp.setBackground(new java.awt.Color(255, 237, 219));
        otp.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        otp.setEnabled(false);
        otp.setMargin(new java.awt.Insets(1, 3, 1, 1));
        otp.setOpaque(true);
        otp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otpActionPerformed(evt);
            }
        });
        otp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                otpKeyPressed(evt);
            }
        });
        jPanel3.add(otp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 290, 50));

        verifyotp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        verifyotp.setText("Verify OTP");
        verifyotp.setEnabled(false);
        verifyotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyotpActionPerformed(evt);
            }
        });
        jPanel3.add(verifyotp, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));

        sendotp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sendotp.setText("Send  OTP");
        sendotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendotpActionPerformed(evt);
            }
        });
        jPanel3.add(sendotp, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 237, 219));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Password");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setText("Confirm Password");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 270, 50));

        pass2.setText("password000000000000000000");
        pass2.setEnabled(false);
        pass2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass2FocusGained(evt);
            }
        });
        jPanel4.add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 290, 50));

        pass.setText("password000000000000000000");
        pass.setEnabled(false);
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFocusGained(evt);
            }
        });
        jPanel4.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 290, 50));

        jLabel6.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel6.setText("Already have a account?");

        signin.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        signin.setText("Register");
        signin.setBorder(null);
        signin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin.setEnabled(false);
        signin.setMargin(new java.awt.Insets(2, 2, 2, 2));
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 255));
        jButton2.setText("LogIn");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 237, 219));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Make sure to write carfefully your details .");
        jLabel8.setToolTipText("");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -9, 670, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel9.setText(".");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -76, 20, 140));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Adhar No.");

        adhar.setBackground(new java.awt.Color(255, 237, 219));
        adhar.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        adhar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        adhar.setDoubleBuffered(true);
        adhar.setEnabled(false);
        adhar.setMargin(new java.awt.Insets(1, 3, 1, 1));
        adhar.setOpaque(true);
        adhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adharActionPerformed(evt);
            }
        });
        adhar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adharKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240)
                .addComponent(signin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(adhar, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adhar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addGap(30, 30, 30)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        user_login u_l = new user_login();
        u_l.show();
        
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        // TODO add your handling code here:
        if(username.getText().length() == 0 || pass.getText().length() == 0|| pass2.getText().length() == 0 ||adhar.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(this,"Data Field cannot be empty.","Alert",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(adhar.getText().length() != 12)
        {
            JOptionPane.showMessageDialog(this,"Invalid Adhar number.","Alert",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!pass.getText().equals(pass2.getText()))
        {
            JOptionPane.showMessageDialog(this,"Passwords donot match with each other.","Alert",JOptionPane.ERROR_MESSAGE);
            return;
        }
        submit_data();        
        JOptionPane.showMessageDialog(this,"You are now being directed to Login Page.\n Login there to Enter Dashboard.","Info",JOptionPane.NO_OPTION);
        user_login ul = new user_login();
        ul.show();        
        dispose();
    }//GEN-LAST:event_signinActionPerformed
    
    private void submit_data() {
        try
        {
            String querry = "insert into signup(Name,password,email,adhar) values(?,?,?,?)";
            stm = con.prepareStatement(querry);
            stm.setString(1,username.getText());
            stm.setString(2,pass.getText());
            stm.setString(3,mail.getText());
            stm.setString(4,adhar.getText());
            stm.execute();
            
            String sql = "select id from signup where adhar = " + adhar.getText();
            stm = con.prepareStatement(sql);
            //stm = con.prepareStatement(sql);
            data = stm.executeQuery(sql);
            String regis= "";
            String id = "";
            while(data.next())
            {
                id = data.getString(1);
                Date d = new Date();
                int year = d.getYear() + 1900;
                int month = d.getMonth();
                regis =  year + "" + month + "" +"" + id;
            }
            querry= "update signup set referid = " + regis + " where id = " + id;
            stm = con.prepareStatement(querry);
            stm.execute();
            start_refer_mail(regis);            
            JOptionPane.showMessageDialog(this,"Your response has been recoreded. \n Your registration id is " + regis + " .\n And it is " +  "being mailed to you at your given Email Address.","Info",JOptionPane.NO_OPTION);
            
        }
        catch(Exception e)
        {
            if("class java.sql.SQLIntegrityConstraintViolationException".equals(e.getClass().toString()))
            {
                JOptionPane.showMessageDialog(this,"Same adhar data found in database.","Info",JOptionPane.NO_OPTION);
                return;
                
            }
            System.out.println(e.getClass().toString());
            JOptionPane.showMessageDialog(this,"Errro while submitting response.","Info",JOptionPane.NO_OPTION);
        }
    }
    
    private void otpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otpActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyReleased
        // TODO add your handling code here:
        int pos = username.getCaretPosition();
        username.setText(username.getText().toUpperCase());
        username.setCaretPosition(pos);
    }//GEN-LAST:event_usernameKeyReleased

    private void otpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otpKeyPressed
        // TODO add your handling code here:
        String str = otp.getText();
        if(evt.getExtendedKeyCode() == KeyEvent.VK_DELETE ||  evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE)
        {
            if(str.length() > 0)
            {
                str = str.substring(0,str.length()-1);
                System.out.println(str.length());
                otp.setText(str);
                
            }
            if(str.length() <= 6)
            {
                verifyotp.setEnabled(false);            
            }
            return;            
        }
        if(str.length() == 5){
            verifyotp.setEnabled(true);
            
        }
        
        if(str.length() < 6){
            if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')
            {
               // phone1.setEditable(true);
                otp.setText(otp.getText() + "" + evt.getKeyChar());
            }
        }
        
        otp.setEditable(false);
    }//GEN-LAST:event_otpKeyPressed

    private void sendotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendotpActionPerformed
        // TODO add your handling code here:
        String email = mail.getText();
        if(email.length() == 0)
        {
            JOptionPane.showMessageDialog(this,"First Enter your email","Alert",JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{
            sendotp.setEnabled(false);
            otp.setEnabled(true);
            otp.setBackground(new java.awt.Color(255, 198, 172));
            start_mail(email);
            
        }       

    }//GEN-LAST:event_sendotpActionPerformed
    private void start_refer_mail(String regis){
        String msg = "Hello! "+ username.getText()+ " . Your registration id is " + regis + "'. you can now proceed for login in our app.";
        String subject = "I.I.P.P.  :  Signup Conformation";
        String to = old_mail;
        String from = "i.i.p.p.confromation@gmail.com";        
        send_text_email(msg,subject,to,from);
        
    }
    private  void start_mail(String to) {
        old_mail = to;
        Random random = new Random();
        int random_otp = random.nextInt(100000, 999999);
        OTP = "" + random_otp;
        
        String msg = "Hello! "+ username.getText()+ " . Your one time OTP for email verification is   '" + random_otp + "'. Do  not share it with others. This is valid for only 5 minutes.";
        String subject = "I.I.P.P.  :  Signup Conformation";
        String from = "i.i.p.p.confromation@gmail.com";        
        send_text_email(msg,subject,to,from);
        
    }

    private void send_text_email(String msg, String subject, String to, String from) 
    {
        Properties properties = System.getProperties();        
        // host setup
        
        properties.put("mail.smtp.host","smtp.gmail.com");
        properties.put("mail.smtp.port","465");
        properties.put("mail.smtp.ssl.enable","true");
        properties.put("mail.smtp.auth","true");
        
        // getting session object
        Session session = Session.getInstance(properties, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication("i.i.p.p.confromation@gmail.com", "cgmyrbpnqkluksxk");
            }
        });
        //session.setDebug(true);
        MimeMessage m = new MimeMessage(session);
        
        try
        {   
            m.setFrom(from);
            m.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
            m.setSubject(subject);
            m.setText(msg);            
            Transport.send(m);            
            jLabel1.setText("Msg Sent");            
        }
        catch(Exception e)
        {
            
            System.out.println(e);            
        }       
    }
    
    
    private void verifyotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyotpActionPerformed
        // TODO add your handling code here:
        if(otp.getText().equals(OTP))
        {
            sendotp.setEnabled(false);
            verifyotp.setEnabled(false);
            pass.setEnabled(true);
            adhar.setEnabled(true);
            adhar.setBackground(new java.awt.Color(255, 198, 172));
            pass.setBackground(new java.awt.Color(255, 198, 172));
            pass2.setEnabled(true);
            pass2.setBackground(new java.awt.Color(255, 198, 172));
            signin.setEnabled(true);            
        }
        else{
            JOptionPane.showMessageDialog(this,"O.T.P. not valid!","Alert",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_verifyotpActionPerformed

    private void adharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adharActionPerformed

    private void adharKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adharKeyPressed
        // TODO add your handling code here:
        String str = adhar.getText();
        if(evt.getExtendedKeyCode() == KeyEvent.VK_DELETE ||  evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE)
        {
            if(str.length() > 0)
            {
                adhar.setText(str.substring(0,str.length()-1));
            }
        }
        
        if(str.length() < 12){
            if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')
            {
               // phone1.setEditable(true);
                adhar.setText(adhar.getText() + "" + evt.getKeyChar());
            }
        }
        adhar.setEditable(false);
    }//GEN-LAST:event_adharKeyPressed

    private void mailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailKeyReleased
        // TODO add your handling code here:
        new_mail = mail.getText();
        //System.out.println(new_mail);
        if(!new_mail.equals(old_mail))
        {
            //System.out.println(new_mail);
            old_mail = new_mail;
            otp.setEnabled(false);
            sendotp.setEnabled(true);
        }
        
    }//GEN-LAST:event_mailKeyReleased

    private void passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusGained
        // TODO add your handling code here:
        pass.setText("");
    }//GEN-LAST:event_passFocusGained

    private void pass2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass2FocusGained
        // TODO add your handling code here:
        pass2.setText("");
    }//GEN-LAST:event_pass2FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adhar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField otp;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JButton sendotp;
    private javax.swing.JButton signin;
    private javax.swing.JTextField username;
    private javax.swing.JButton verifyotp;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() 
    {   
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("a1.png")));        
    }

    
}
